= Welcome to Zwitscher

Welcome to Zwitscher, a microblogging client for Android, that is licensed
under the ASL V2 license (as is Twitter4j) -- see LICENSE.txt
I know that this is not the first one and far from working good.
It is first a "real" project for me to get into Android programming.

Currently the client uses the twitter4j library, but I think in the
longer term, I will directly go to use REST/Json, as there is already
native Json support in the Android libraries
- this lets me learn that part
- it scales down the application size.

For the start I did not really set a target Android platform - at the end
it had to work on my HTC Desire with Android 2.2.
This has been changed since and futher development on the master
branch will only be for Api level 14 and later, which corresponds
to Android 4.0+. The statistics from the market show that > 65%
of all devices that run Zwitscher run on 4.0+

Zwitscher hat been translated into some languages - if you want
to help translating into new languages, ping me.

If you find issues or want new features, please open
an issue on the github tracker at https://github.com/pilhuhn/ZwitscherA/issues

== ATTENTION ON HACKING THE SOURCE

As Twitter.com is not really ready to handle open source projects,
you need to register the app at Twitter and then provide a class
Token (renamed from TwitterConsumerToken) that looks like this with the values Twitter
provided you with put in:

[source,java]
----
    package de.bsd.zwitscher;

    public class Tokens
    {

        public static String consumerKey = "replaceWithKey";
        public static String consumerSecret = "replaceWithSecret";
        public static boolean xAuthEnabled = false;

        public static final String readItLaterToken = "";

        public static String tweetMarkerToken = "";

        public static String bugSenseKe = "";
    }
----

To obtain these Twittter-Tokens, go to http://twitter.com/apps and log in.
Then click on "Register an Application" and give some details.
When this is done you will end up on a page that lists application
details including `consumerKey` and `consumerSecret`.
As Twitter by default does not enable xAuth, the third parameter
needs to be set to `false` to go through the "normal" oAuth procedure of
logging in.

Zwitscher has meanwhile progressed enough to be available on the Android market.
For this version you don't need to obtain any tokens.

== Support for ReadItlater (http://http://readitlaterlist.com/)


If you want to add Suppor for ReadItlater, you need to get a Token
and put it into above Token file as well

== Support for TweetMarker

Zwitscher can now also sync last read information with
TweetMarker.com (and thus with clients like Twitterriffic).
To enable this, you also need to have a token in above tokens file

== Support for BugSense

If you supply a token value for bugSense, BugSense crash reporting
is turned on.



